name: Challenge 3

on: push

env:
    ARTIFACT_NAME: Artefacto

jobs: 
    Main:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout
            uses: actions/checkout@v2

        -   name: Upload 
            uses: actions/upload-artifact@v4
            with:
                name: ${{ env.ARTIFACT_NAME }}
                path: .
                



